In [1]:
#Q1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.#

import numpy as np

l1 = [0,1,2,3,4,5]
arr = np.array(l1)
print(arr)
arr.dtype


[0 1 2 3 4 5]


dtype('int64')

In [4]:
arr.dtype

dtype('int64')

In [9]:
#Q2.Given a NumPy array 'arr', check if its data type is float64.#

arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print("Given data type is float64 ?", is_float64), 

Given data type is float64 ? True


(None,)

In [11]:
#Q3, Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers#

l2 = [1,2,3+4j,5,6+5j,7,8+9j]
arr = np.array(l2)
print(arr.dtype)

complex128


In [13]:
l2 = [1,2,3+4j,5,6+5j,7,8+9j]
arr = np.array(l2,dtype = np.complex128)
print(arr.dtype)

complex128


In [22]:
#Q4. Convert an existing NumPy array 'arr' of integers to float32 data type#

l1 = [0,1,2,3,4,5]
arr = np.array(l1)
print("Actual Data :",l1)
print("Datatype:", arr.dtype)
is_float32 = arr.astype(np.float32)
print("Converted array",is_float32)
print("Converted Datatype", is_float32.dtype)

Actual Data : [0, 1, 2, 3, 4, 5]
Datatype: int64
Converted array [0. 1. 2. 3. 4. 5.]
Converted Datatype float32


In [25]:
#Q5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision #

arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print("Actual Data", arr)
print("Datatype",arr.dtype)
a_float32 = arr.astype(np.float32)
print("Converted array",a_float32)
print("Converted Datatype", a_float32.dtype)

Actual Data [1.5 2.6 3.7]
Datatype float64
Converted array [1.5 2.6 3.7]
Converted Datatype float32


In [28]:
#Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type#

array_attributes = input("Enter the array")

arr1 = np.array(array_attributess)
arr1
print("shape", arr1.shape)
print("size",arr1.size)
print("Datatype",arr1.dtype)

In [32]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    datatype = arr.dtype
    return shape, size, datatype

arr1 = np.array([[3, 4, 5], [7, 8, 9]])
shape, size, datatype = array_attributes(arr1)

print("shape",shape)
print("size",size)
print("Datatype",datatype)

shape (2, 3)
size 6
Datatype int64


In [39]:
#Q7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality#

def array_dimension(arr):
    return arr.ndim

arr1 = np.array([1,2,3.4])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([[[1],[2],[3],[4]],[[5],[6],[7],[8]]])

print("Dimession of arr1",array_dimension(arr1))
print("Dimession of arr2",array_dimension(arr2))
print("Dimession arr3",array_dimension(arr3))


Dimession of arr1 1
Dimession of arr2 2
Dimession arr3 3


In [43]:
#Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.#

def item_size_info(arr):
    size = arr.size
    total_size_bytes = arr.nbytes
    return size, total_size_bytes

arr1 = np.array([1,2,3,4])
size, total_size_bytes = item_size_info(arr1)

print("Size",size)
print("total_size_bytes",total_size_bytes)

Size 4
total_size_bytes 32


In [44]:
def item_size_info(arr):
    size = arr.itemsize
    total_size_bytes = arr.nbytes
    return size, total_size_bytes

arr1 = np.array([1,2,3,4])
size, total_size_bytes = item_size_info(arr1)

print("Size",size)
print("total_size_bytes",total_size_bytes)

Size 8
total_size_bytes 32


In [45]:
#Q9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array#

def array_strides(arr):
    return arr.strides
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("Strides of Array", array_strides(arr1))

Strides of Array (32, 8)


In [48]:
#Q10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shap and strides of the array#

def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
shape,strides = shape_stride_relationship(arr1)
print ("Shape of array",shape)
print("Stides of array",strides) 

Shape of array (2, 4)
Stides of array (32, 8)


In [6]:
#Q11.Create a function `create_zeros_array` that takes an integer `n` as input an returns a NumPy array ofzeros with `n` elements. #

import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

arr1 = np.array([2,2])
print("Array with n elements", create_zeros_array(arr1))

Array with n elements [[0. 0.]
 [0. 0.]]


In [4]:
def create_zeros_array(n):
    return np.zeros(n)

arr1 = np.array([1, 2, 3, 4, 5])
print("Array with n elements:", create_zeros_array(len(arr1)))

Array with n elements: [0. 0. 0. 0. 0.]


In [12]:
#Q12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`#

def create_ones_matrix(rows, col):
    return np.ones((rows,col))
matrix = create_ones_matrix(3, 4)
print("Matrix",matrix)

    

Matrix [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#Q13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step#

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
arr1 = generate_range_array(1,10,0.2)
print("Range",arr1)

Range [1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [24]:
#Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).#

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)
arr1 = generate_linear_space(1,2,10)
print("Linear Space",arr1)

Linear Space [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [26]:
#Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.#

def create_identity_matrix(n):
    return np.eye(n)
identity_matrix = create_identity_matrix(5)
print("Identity Matrix",identity_matrix)

Identity Matrix [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
#Q16.Write a function that takes a Python list and converts it into a NumPy array #

l = [1,2,3,4,5]
arr = np.array(l)
arr


array([1, 2, 3, 4, 5])

In [29]:
def python_list(lis):
    return np.array(lis)
l1 = [1,2,3,4]
arr = python_list(l1)
print(arr)

[1 2 3 4]


In [30]:
#Q17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data #

org_array = np.array([1,2,3,4,5])
view_array = org_array.view()
view_array[0] = 10
print("Array",org_array)
print("View Array", view_array)

Array [10  2  3  4  5]
View Array [10  2  3  4  5]


In [50]:
#Q18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.#

def concatenates_array(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
concat_axis0 = concatenates_array(arr1, arr2, axis=0)#axis 0 
print("Cancatination of Twp Numpy arrays", concat_axis0)

concat_axis1 = concatenate_arrays(array1, array2, axis=1) #axis1 
print("Concatenate along axis 1:\n", concat_axis1)

Cancatination of Twp Numpy arrays [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [52]:
#Q19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`#

def concatenate_horizontally(arr1, arr2, axis=1):
    return np.concatenate((arr1,arr2),axis=axis)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[3,4,5],[6,7,8]])

concat_axis1 = concatenate_horizontally(arr1,arr2, axis=1)
print("Concatenat Horizantally",concat_axis1)

Concatenat Horizantally [[1 2 3 4 5]
 [3 4 6 7 8]]


In [56]:
#Q20.Write a function that vertically stacks multiple NumPy arrays given as a list#

def vertical_stack(arr):
    return np.vstack(arr)
arr_list = [
    np.array([[1, 2], [3, 4]]),
    np.array([[5, 6], [7, 8]])]
stacked_arr = vertical_stack(arr_list)
print("Vertically Stacked Array:\n", stacked_arr)


Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
#Q21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size #

def array_range(start,stop,step):
    return np.arange(start,stop+step,step)
arr = array_range(1,20,2)
print("Array",arr)

Array [ 1  3  5  7  9 11 13 15 17 19 21]


In [58]:
#Q22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive) #

def spaced_array(start, stop, num):
    return np.linspace(start, stop, num)
array = spaced_array(0, 1, 10)
print("Array:", array)

Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [59]:
#Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive) #

def log_array(start,stop,num):
    return np.logspace(start,stop,num)
array = log_array(0,1,10)
print("Array",array)

Array [ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


In [61]:
#Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100 #

import pandas as pd

n_arr = np.random.randint(1,100,(5,3))
df = pd.DataFrame(n_arr, columns=['col1','col2','col3'])
df
                                  
        

col1  col2  col3
0    54    96     4
1    40    73    98
2    34    39    15
3    27    60    70
4    25    93    56

In [66]:
#Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame#

def replace_negatives_with_zeros(df, column_name):
    if column_name in df.columns:
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        print(f"Column '{column_name}' does not exist in the DataFrame.")
    
    return df
data = {
    'A': [10, -5, 3, -2, 7],
    'B': [-1, 6, -3, 8, -4]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_modifiedA = replace_negatives_with_zeros(df, 'A')

print("\nDataFrame after replacing negatives in column 'A':")
print(df_modifiedA)

df_modifiedB = replace_negatives_with_zeros(df, 'B')

print("\nDataFrame after replacing negatives in column 'B':")
print(df_modifiedB)

Original DataFrame:
    A  B
0  10 -1
1  -5  6
2   3 -3
3  -2  8
4   7 -4

DataFrame after replacing negatives in column 'A':
    A  B
0  10 -1
1   0  6
2   3 -3
3   0  8
4   7 -4

DataFrame after replacing negatives in column 'B':
    A  B
0  10  0
1   0  6
2   3  0
3   0  8
4   7  0


In [70]:
#Q26.Access the 3rd element from the given NumPy array. #

arr = np.array([10, 20, 30, 40, 50])
third_elemt = arr[2]
print("Thirsd Elements", third_elemt)

Thirsd Elements 30


In [72]:
#Q27.Retrieve the element at index (1, 2) from the 2D NumPy array. #

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
retrive_arr = arr_2d[1,2]
print("Retrive 2D array",retrive_arr)


Retrive 2D array 6


In [73]:
#Q28.Using boolean indexing, extract elements greater than 5 from the given NumPy array. #

arr = np.array([3, 8, 2, 10, 5, 7])
greater = arr > 5
greater_array = arr[greater]
print("greater than 5",greater_array)

greater than 5 [3 2]


In [75]:
#Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array#

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
slicing_arr = arr[2:6]
print("slicing to extract",slicing_arr)

slicing to extract [3 4 5 6]


In [86]:
#Q30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array #

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
silicing_arr = arr_2d[0:3, 1:3]
print("slicing to extract",silicing_arr)

slicing to extract [[2 3]
 [5 6]
 [8 9]]


In [2]:
#Q31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array#

def extract_elements(arr_2d, indices):
    rows, cols = zip(*indices)
    extracted_elements = arr_2d[rows, cols]
    return extracted_elements
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = [(0, 1), (1, 2), (2, 0)]
result = extract_elements(arr_2d, indices)
print("Extracted elements:", result)

Extracted elements: [2 6 7]


In [9]:
#Q32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing. #

def filters_elements_greater(arr, threshold):
    greater_than = arr > threshold
    greater_array = arr[greater_than]
    return greater_array

arr = np.array([1,2,5,6,7,8])
threshold = 2
greater = filters_elements_greater(arr,threshold)
print("Greater Than", greater)



Greater Than [5 6 7 8]


In [10]:
#Q33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension#

def extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices):
    extracted_elements = arr_3d[row_indices, col_indices, depth_indices]
    return extracted_elements
arr_3d = np.array([[[2, 2, 3],
                    [3, 5, 6],
                    [7, 8, 9]],
                   
                   [[12, 10, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[17, 19, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
depth_indices = np.array([2, 0, 1])
result = extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices)
print("Extracted elements:", result)

Extracted elements: [ 6 16 19]


In [12]:
#Q34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter_elements(arr, condi1, condi2):
    if isinstance(condi1, (int, float)):
        condi1 = arr > condi1
    if isinstance(condi2, (int, float)):
        condi2 = arr < condi2
    combined_condition = condi1 & condi2
    filtered_elements = arr[combined_condition]
    return filtered_elements
arr = np.array([1, 5, 8, 12, 3, 7])
condi1 = 5  
condi2 = 10 
result = filter_elements(arr, condi1, condi2)
print("Filtered elements:", result)

Filtered elements: [8 7]


In [13]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays #

def extract_elements_2d(arr_2d, row_indices, col_indices):
    if len(row_indices) != len(col_indices):
        raise ValueError("row_indices and col_indices must have the same length")
    extracted_elements = arr_2d[row_indices, col_indices]
    return extracted_elements
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", result)

Extracted elements: [2 6 7]


In [15]:
#Q36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting#

arr = np.array([[2, 2, 3],
                [3, 5, 2],
                [6, 8, 9]])
addition = arr + 5
print("Original array:", arr)
print("Array after adding 5:\n", addition)

Original array: [[2 2 3]
 [3 5 2]
 [6 8 9]]
Array after adding 5:
 [[ 7  7  8]
 [ 8 10  7]
 [11 13 14]]


In [19]:
#Q37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.#

arr1 = np.array([[1,2,3]])
arr2 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
multiply = arr1 * arr2
print("Multiplication of arr1 and arr2", multiply)

Multiplication of arr1 and arr2 [[[ 1  4  9]
  [ 4 10 18]
  [ 7 16 27]]]


In [21]:
#Q38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.#

arr1 = np.array([1,2,3,4])
arr2 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]]])

add1 = arr1 + arr2
print("Addition of arr1 and arr2",add1)

ValueError: operands could not be broadcast together with shapes (4,) (1,4,3) 

In [23]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]]])
reshape = np.reshape(arr1, (4,1))
print("reshape",reshape)
addition = reshape + arr2
print("Addition of arr1 and arr2",addition)

rshape [[1]
 [2]
 [3]
 [4]]
Addition of arr1 and arr2 [[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]
  [14 15 16]]]


In [24]:
#Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting#

arr1 = np.array([[1],
                [2],
                [3]])
arr2 = np.array([[4,5,6]])
add = arr1 + arr2
print("Addition",add)

Addition [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [31]:
#Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility#

arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,2],
                 [3,4]])
arr2_broadcasted = np.reshape(arr2, (2, 1, 2)) 
arr2_broadcasted = np.repeat(arr2_broadcasted, 3, axis=1) 
multiplication = arr1[:, :, np.newaxis] * arr2_broadcasted 
result = np.squeeze(multiplication, axis=2) 
print("Multiplication result:\n", result)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [37]:
#Q41.  Calculate column wise mean for the given array#

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
column_wise_mean = np.mean(arr,axis=0)
print("column wise mean",column_wise_mean)


column wise mean [2.5 3.5 4.5]


In [41]:
#Q42. Find maximum value in each row of the given array:#

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
maximum_value = np.max(arr,axis = 1)
print("Maximum value in each row",maximum_value)

Maximum value in each row [3 6]


In [43]:
#Q43. For the given array, find indices of maximum value in each column.#

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
indices_maximum_col_value = np.argmax(arr,axis = 0)
print("maximum value in each column",indices_maximum_col_value)


maximum value in each column [1 1 1]


In [52]:
#Q44. For the given array, apply custom function to calculate moving sum along rows#

def moving_sum(arr, window_size):
    if window_size <= 0 or window_size > arr.shape[1]:
        raise ValueError("Window size must be a positive integer and less than or equal to the number of columns.")
    result = []
    for row in arr:
        row_sum = np.convolve(row, np.ones(window_size, dtype=int), mode='valid')
        result.append(row_sum)
    return np.array(result)
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
window_size = 2
moving_sum_result = moving_sum(arr, window_size)
print("Moving sum along rows:", moving_sum_result)


Moving sum along rows: [[ 3  5]
 [ 9 11]]


In [55]:
#Q45.  In the given array, check if all elements in each column are even#

arr = np.array([[2, 4, 6], 
                [3, 5, 7]])
even_mask = (arr % 2 == 0)
even_elements = np.all(even_mask, axis = 0)
print("Even elements in each column" ,even_elements)

Even elements in each column [False False False]


In [59]:
#Q46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. #

import numpy as np

def reshape_array(original_array, m, n):
    if original_array.size != m * n:
        raise ValueError("The total number of elements does not match the target shape.")
    reshaped_matrix = original_array.reshape(m, n)
    return reshaped_matrix
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2  
n = 3 
reshaped_matrix = reshape_array(original_array, m, n)

print("Reshaped matrix:\n", reshaped_matrix)


Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [61]:
#Q47.  Create a function that takes a matrix as input and returns the flattened array.#

def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3], 
                         [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [69]:
#Q48. Write a function that concatenates two given arrays along a specified axis#

def concatenate_array(array1, array2, axis=0):
    concatenates_array = np.concatenate((array1, array2), axis=axis)
    return concatenates_array
array1 = np.array([[1, 2], 
                   [3, 4]])
array2 = np.array([[5, 6], 
                   [7, 8]])
concatinate_axis0 = concatenate_array(array1, array2, axis=0)
concatinate_axis1 = concatenate_array(array1, array2, axis=1)

print("Concatinate coulmn wise",concatinate_axis0)
print("Concatinate coulmn wise",concatinate_axis1)

Concatinate coulmn wise [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatinate coulmn wise [[1 2 5 6]
 [3 4 7 8]]


In [71]:
#Q49. Create a function that splits an array into multiple sub-arrays along a specified axis#

def split_array(array,indices,axis =0):
    sub_arrays = np.split(array,indices,axis = axis)
    return sub_arrays
original_array = np.array([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])
sub_arrays =split_array(original_array,[1,2],axis =0)
print("Sub arrays along axis =0\n", sub_arrays)

Sub arrays along axis =0
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [88]:
#Q50. Write a function that inserts and then deletes elements from a given array at specified indices#

def insert_and_delete_elements(array, indices_insert, values_insert, indices_delete):
    array_to_inserts = np.insert(array, indices_insert, values_insert)
    array_after_deletion = np.delete(array_to_inserts, indices_delete)
    return array_after_deletion
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]  
values_to_insert = [10, 11] 
indices_to_delete = [1, 3]   
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified array after insertion and deletion:", modified_array)

Modified array after insertion and deletion: [ 1 10  4 11  5]
