In [3]:
#Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`#

import numpy as np

arr1 = np.random.randint(0,10,size =(10,))
arr2 = np.arange(1,11)
addition = arr1+arr2
print("Arr1",arr1)
print("Arr2",arr2)
print("Element wise addition",addition)

Arr1 [3 5 0 8 0 8 3 4 0 3]
Arr2 [ 1  2  3  4  5  6  7  8  9 10]
Element wise addition [ 4  7  3 12  5 14 10 12  9 13]


In [13]:
#Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise

arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
Subtract = arr1-arr2
print("Arr1",arr1)
print("Arr2",arr2)
print("Substarcation",Subtract)

Arr1 [10  9  8  7  6  5  4  3  2  1]
Arr2 [ 1  2  3  4  5  6  7  8  9 10]
Substarcation [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [15]:
#Q53.  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.#

arr1 = np.random.randint(0,5,size=(5,))
arr2 = np.arange(1,6)
Multiplication = arr1 * arr2
print("Arr1",arr1)
print("Arr2",arr2)
print("Multiplication of Array",Multiplication)

Arr1 [1 2 3 1 4]
Arr2 [1 2 3 4 5]
Multiplication of Array [ 1  4  9  4 20]


In [18]:
#Q54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.#

arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
Multiplication = arr1 / arr2
print("Arr1",arr1)
print("Arr2",arr2)
print("Multiplication of Array",Multiplication)

Arr1 [ 2  4  6  8 10]
Arr2 [1 2 3 4 5]
Multiplication of Array [2. 2. 2. 2. 2.]


In [19]:
#Q55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise#

arr1 = np.arange(1,6)
arr2 = arr1[::-1]
exponentiation_power = np.power(arr1,arr2)
print("Arr1",arr1)
print("Arr2",arr2)
print("exponentiation of `arr1` raised to the power of `arr2` element-wise",exponentiation_power)

Arr1 [1 2 3 4 5]
Arr2 [5 4 3 2 1]
exponentiation of `arr1` raised to the power of `arr2` element-wise [ 1 16 27 16  5]


In [22]:
#Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings#

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = "hello"
specific_substring = np.char.count(arr, substring)
counts_the_occurrences = np.sum(specific_substring)
print("specific substring",specific_substring)
print("counts_the_occurrences",counts_the_occurrences)

specific substring [1 0 1 0 1]
counts_the_occurrences 3


In [24]:
#Q57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(c):
    return ''.join([char for char in c if not char.isupper()])
uppercase_char = np.vectorize(extract_uppercase)(arr)
print("Extracts uppercase characters",uppercase_char)

Extracts uppercase characters ['ello' 'orld' 'pen' '']


In [26]:
#Q58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string#

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replaces_occurrence(arr,old_substring,new_substring):
    return np.char.replace(arr,old_substring,new_substring)
replaces_occurrences_substring = replaces_occurrence(arr,"grape","orange")
print("Original Array",arr)
print("Replaces occurrences of a substring",replaces_occurrences_substring)

Original Array ['apple' 'banana' 'grape' 'pineapple']
Replaces occurrences of a substring ['apple' 'banana' 'orange' 'pineapple']


In [32]:
#Q59.Write a function that concatenates strings in a NumPy array element-wise#

def concatinate_strings(arr1,arr2):
    return np.char.add(arr1,arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
cocatination = concatinate_strings(arr1,arr2)
print("Arr1",arr1)
print("Arr2",arr2)
print("Concatenation of strings",cocatination)

Arr1 ['Hello' 'World']
Arr2 ['Open' 'AI']
Concatenation of strings ['HelloOpen' 'WorldAI']


In [35]:
#Q60.Write a function that finds the length of the longest string in a NumPy array#

def length_of_string(arr):
    vectorized_len = np.vectorize(len)
    lengths = vectorized_len(arr)
    return np.max(lengths)
        
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("length of longest string",length_of_string(arr))

length of longest string 9


In [39]:
#Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions#

arr1 = np.random.randint(1,1001,size = 100)
print("Dataset",arr1)
print("Mean",np.mean(arr1))
print("Median",np.median(arr1))
print("variance",np.var(arr1))
print("Standare Devaition",np.std(arr1))


Dataset [ 381  610  347   74  408  737  472  166  590  886  187 1000  562  695
  661  703  130  995  221  802  607  804  749  391  311   59  612  754
   43  983  867  733  165  394  946   89  693   56  470  277    4  841
  418   58  533  438  496  349  257  431  165  750   89  143  229   74
  363  438  923  802  317  381  755  444   67  599   66  493  666  466
  393  331  133  947  776  776  983  879  731  271  990  558  841   44
  636  372  984   87  644  199  210  324  567  548  410  207  254  413
  286  190]
Mean 476.69
Median 438.0
variance 81702.89389999998
Standare Devaition 285.83718075155997


In [41]:
#Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset#

arr1 = np.random.randint(1,101,size=50)
print("25th percentiles of the dataset",np.percentile(arr1,25))
print("75th percentiles of the dataset",np.percentile(arr1,75))


25th percentiles of the dataset 24.5
75th percentiles of the dataset 77.5


In [42]:
#Q63.  Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function#

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
correlation_coefficient = np.corrcoef(arr1,arr2)
print("Correlation Coefficient between two arrays",correlation_coefficient)

Correlation Coefficient between two arrays [[1. 1.]
 [1. 1.]]


In [43]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
correlation_matrix = np.corrcoef(arr1,arr2)
correlation_coefficient = correlation_matrix[0, 1]
print("Correlation Coefficient between two arrays",correlation_coefficient)


Correlation Coefficient between two arrays 1.0


In [49]:
#Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function#

arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,5,(3,3))
matrix_multiplication = np.dot(arr1,arr2)
print("Arr1",arr1)
print("Arr2",arr2)
print("Matrix Multiplication",matrix_multiplication)

Arr1 [[2 1 1]
 [1 2 3]
 [2 1 2]]
Arr2 [[4 3 2]
 [3 1 3]
 [4 3 4]]
Matrix Multiplication [[15 10 11]
 [22 14 20]
 [19 13 15]]


In [58]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles#

arr1 = np.random.randint(10,1001,size = 50)
print("10th percentile :",np.percentile(arr1,10))
print("50th percentile :",np.percentile(arr1,50))
print("50th percentile :",np.median(arr1))
print("90th percentile :",np.percentile(arr1,90))
print("First quartiles:",np.percentile(arr1,25)) #First quartiles is 25th percentile
print("third quartiles:",np.percentile(arr1,75)) #third quartiles is 75th percentile

10th percentile : 104.10000000000001
50th percentile : 496.0
50th percentile : 496.0
90th percentile : 854.8000000000001
First quartiles: 197.0
third quartiles: 753.0


In [63]:
#Q66 Create a NumPy array of integers and find the index of a specific element#

arr1 = np.array([1,2,3,6])
elements = 3
index_elements = np.where(arr1 == elements)[0]
print("Index of specfic elements",index_elements)


Index of specfic elements [2]


In [66]:
arr1 = np.array([1,2,3,6])
elements = 3
index_elements = np.where(arr1 == elements)[0]
print("Index of specific element (", elements, "):", index_elements)

Index of specific element ( 3 ): [2]


In [70]:
#Q67. Generate a random NumPy array and sort it in ascending order#

arr1 = np.random.randint(1,10,size = 10 )
ascending_order = np.sort(arr1)
print("Original Array",arr1)
print("Ascending Order Array",ascending_order)

Original Array [9 3 7 5 9 8 8 9 8 7]
Ascending Order Array [3 5 7 7 8 8 8 9 9 9]


In [73]:
#Q68.  Filter elements >20  in the given NumPy array#

arr = np.array([12, 25, 6, 42, 8, 30])
greater_than = arr[arr>20]
print("Filter elements >2",greater_than)

Filter elements >2 [25 42 30]


In [74]:
arr = np.array([12, 25, 6, 42, 8, 30])
greater_than = arr>20 
print("Filter elements >2",greater_than)

Filter elements >2 [False  True False  True False  True]


In [78]:
#Q69.Filter elements which are divisible by 3 from a given NumPy array#

arr = np.array([1, 5, 8, 12, 15])
devide_by = arr[arr % 3 == 0]
print("Original Array",arr)
print("Divisible by 3",devide_by)

Original Array [ 1  5  8 12 15]
Divisible by 3 [12 15]


In [80]:
#Q70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array#

arr = np.array([10, 20, 30, 40, 50])
greater_equal_to = arr[arr >= 20]
less_equal_to = arr[arr <= 40]
print("Original Array",arr)
print("Greater than equal to 20",greater_equal_to)
print("Less Than equal to 40",less_equal_to)

Original Array [10 20 30 40 50]
Greater than equal to 20 [20 30 40 50]
Less Than equal to 40 [10 20 30 40]


In [88]:
#Q71.  For the given NumPy array, check its byte order using the `dtype` attribute byteorder#

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("original array",arr)
print("byte order",byte_order)

original array [1 2 3]
byte order =


In [89]:
#Q72.For the given NumPy array, perform byte swapping in place using `byteswap()`#

arr = np.array([1, 2, 3], dtype=np.int32)
byte_swap = arr.byteswap()
print("original array",arr)
print("byte swap",byte_swap)

original array [1 2 3]
byte swap [16777216 33554432 50331648]


In [95]:
#Q73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()#

arr = np.array([1, 2, 3], dtype=np.int32)
byte_swap = arr.byteswap().newbyteorder()
print("original array",arr)
print("byte swap",byte_swap)

original array [1 2 3]
byte swap [1 2 3]


In [97]:
#Q74.For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`#

arr = np.array([1, 2, 3], dtype=np.int32)
native_bytorder = np.dtype(np.int32).byteorder
array_bytorder = arr.dtype.byteorder
if native_bytorder != array_bytorder and array_bytorder != '|':
    byte_swap = arr.newbyteorder()
else:
    byet_swap = arr
print("Original Array:", arr)
print("Swap byte order conditionally:", byte_swap)  

Original Array: [1 2 3]
Swap byte order conditionally: [1 2 3]


In [102]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`#

arr = np.array([1, 2, 3], dtype=np.int32)
arr_byteorder = np.dtype.byteorder
native_byteorder = np.dtype(np.int32).byteorder
if arr_byteorder != native_byteorder and arr_byteorder != '|':
    print("byte swapping is necessary")
else:
    print("byte swapping is not needed")

byte swapping is necessary


In [113]:
#Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`. #

arr1 = np.arange(1,11)
copy_arr = arr1.copy() 
print("Origonal Arry",arr1)
print("Copied Array",copy_arr)
copy_arr[0] = 20
print("Modified Copy Array",copy_arr)
print("Original Array after moficication",arr1)

#So here we haev used deep copy method, in which after copying array(copy_arr = arr1.copy() ) we did any modification in copied array i.e(copy_arr),it will not
#made any changes in original array#

Origonal Arry [ 1  2  3  4  5  6  7  8  9 10]
Copied Array [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array [20  2  3  4  5  6  7  8  9 10]
Original Array after moficication [ 1  2  3  4  5  6  7  8  9 10]


In [128]:
#Q77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`#

matrix = np.random.randint(1,3,(3,3))
view_slice = matrix[1:,1:]
print("original Matrix", matrix)
print("View Slice",view_slice)
view_slice[1, 1] = 90
print("Modified View slice",view_slice)
print("original Matrix", matrix)

#As per below output we sliced view_slice and modified element by adding [1,1] = 90 in view_slice, after this we checke original matrix got changed#

original Matrix [[1 2 2]
 [1 2 1]
 [2 1 1]]
View Slice [[2 1]
 [1 1]]
Modified View slice [[ 2  1]
 [ 1 90]]
original Matrix [[ 1  2  2]
 [ 1  2  1]
 [ 2  1 90]]


In [129]:
matrix = np.random.randint(1,3,(3,3))
view_slice = matrix[1:]
print("original Matrix", matrix)
print("View Slice",view_slice)
view_slice[1, 1] = 90
print("Modified View slice",view_slice)
print("original Matrix", matrix)

original Matrix [[1 1 1]
 [2 1 2]
 [2 2 1]]
View Slice [[2 1 2]
 [2 2 1]]
Modified View slice [[ 2  1  2]
 [ 2 90  1]]
original Matrix [[ 1  1  1]
 [ 2  1  2]
 [ 2 90  1]]


In [8]:
#Q78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`#

array_a = np.arange(1,13).reshape(4,3)
view_b = array_a[1:3,1:]
addition_viewb = view_b + 5

print("Original Array",array_a)
print("View Slice b:",view_b)
print("Addition view b",addition_viewb)
print("Original Array",array_a)

#As per below2 output we extracted slice b and added 5 intger in view_b, after this we checke doriginal array remains same,i.e no array_a reamian same as decalred#


Original Array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View Slice b: [[5 6]
 [8 9]]
Addition view b [[10 11]
 [13 14]]
Original Array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
#Q79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`#

orig_array = np.arange(1,9).reshape(2,4)
reshaped_view = orig_array.reshape(4,2)
print("Original Array",orig_array)
print("reshaped Array",reshaped_view)
reshaped_view[1,0] = 10
print("Modified Array",reshaped_view)
print("Original Array",orig_array)

#As per below output we have reshaped orig_array and modified reshaped_view by adding 10 from rows 1, orign_array got changed.

Original Array [[1 2 3 4]
 [5 6 7 8]]
reshaped Array [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified Array [[ 1  2]
 [10  4]
 [ 5  6]
 [ 7  8]]
Original Array [[ 1  2 10  4]
 [ 5  6  7  8]]


In [32]:
#Q80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`#

data = np.random.randint(1,20,size =(3,4))
data_copy = data[data > 5] #find greater than 5
print("Original data",data)
print("\nCopied Data:",data_copy)
data_copy[1] = 10 #add 10 at index 1
print("\nmodified data",data_copy)
print("\noriginal data",data)


Original data [[ 2  8  9  2]
 [16  1  5 10]
 [15  6  8  9]]

Copied Data: [ 8  9 16 10 15  6  8  9]

modified data [ 8 10 16 10 15  6  8  9]

original data [[ 2  8  9  2]
 [16  1  5 10]
 [15  6  8  9]]


In [36]:
#Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them#

A = np.random.randint(1,3,(3,3))
B = np.random.randint(11,13,(3,3))
print("Matrix A",A)
print("Matrix B",B)
Addition_of_matrix = A+B
Subtraction_of_matrix = A-B
print("Addition of Matrix",Addition_of_matrix)
print("Substarction of matrix",Subtraction_of_matrix)

Matrix A [[1 2 1]
 [2 1 2]
 [1 1 2]]
Matrix B [[12 12 12]
 [12 11 11]
 [11 11 12]]
Addition of Matrix [[13 14 13]
 [14 12 13]
 [12 12 14]]
Substarction of matrix [[-11 -10 -11]
 [-10 -10  -9]
 [-10 -10 -10]]


In [42]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication#

C = np.random.randint(1,3,(3,2))
D = np.random.randint(1,9,(2,4))
print("Matrix C", C)
print("Matrix D", D)
matrix_multiplication = C @ D
print("Matrix Multiplication",matrix_multiplication)

Matrix C [[1 1]
 [1 1]
 [1 2]]
Matrix D [[7 3 7 8]
 [8 2 3 8]]
Matrix Multiplication [[15  5 10 16]
 [15  5 10 16]
 [23  7 13 24]]


In [44]:
#Q83.Create a matrix `E` and find its transpose#

E = np.random.randint(1,3,(3,3))
tranpose_matrix = np.transpose(E)
print("Original Array",E)
print("\nTranspose of array",tranpose_matrix)
                      

Original Array [[1 2 2]
 [2 2 2]
 [1 1 1]]

Transpose of array [[1 2 1]
 [2 2 1]
 [2 2 1]]


In [46]:
#Q84. Generate a square matrix `F` and compute its determinant#

F = np.random.randint(1,3,(3,3))
determinant = np.linalg.det(F)
print("Original Array",F)
print("Determinant Matrix",determinant)

Original Array [[1 1 2]
 [2 1 1]
 [1 2 2]]
Determinant Matrix 2.9999999999999996


In [49]:
#Q85.Create a square matrix `G` and find its inverse.#

F = np.random.randint(1,3,(3,3))
inverse_matrix = np.linalg.inv(F)
print("Original Array",F)
print("Inverse matrix",inverse_matrix)


Original Array [[2 1 2]
 [2 2 1]
 [1 1 2]]
Inverse matrix [[ 1.00000000e+00 -5.55111512e-17 -1.00000000e+00]
 [-1.00000000e+00  6.66666667e-01  6.66666667e-01]
 [ 0.00000000e+00 -3.33333333e-01  6.66666667e-01]]
